// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ops/ops.proto

package ops

import (
	common "github.com/hb-chen/opskills/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitTaskRequest represents a request to submit a task
type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                                             // User query/request
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_proto_ops_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ops_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ops_ops_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SubmitTaskRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// GetTaskStatusRequest represents a request to get task status
type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_proto_ops_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ops_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ops_ops_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// ListTasksRequest represents a request to list tasks
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Filter by status: pending, running, completed, failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_ops_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ops_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_ops_ops_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CancelTaskRequest represents a request to cancel a task
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_ops_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ops_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ops_ops_proto_rawDescGZIP(), []int{3}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Task represents a task
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Plan          string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Results       []*StepResult          `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_ops_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ops_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_ops_ops_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *Task) GetResults() []*StepResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// StepResult represents the result of a step
type StepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        int32                  `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	SkillName     string                 `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_proto_ops_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ops_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_proto_ops_ops_proto_rawDescGZIP(), []int{5}
}

func (x *StepResult) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *StepResult) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *StepResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StepResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *StepResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_ops_ops_proto protoreflect.FileDescriptor

const file_proto_ops_ops_proto_rawDesc = "" +
	"\n" +
	"\x13proto/ops/ops.proto\x12\fopskills.ops\x1a\x1cgoogle/api/annotations.proto\x1a\x19proto/common/common.proto\"\xa9\x01\n" +
	"\x11SubmitTaskRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12C\n" +
	"\x06params\x18\x02 \x03(\v2+.opskills.ops.SubmitTaskRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"[\n" +
	"\x10ListTasksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xe9\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\x122\n" +
	"\aresults\x18\x05 \x03(\v2\x18.opskills.ops.StepResultR\aresults\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x8c\x01\n" +
	"\n" +
	"StepResult\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\x05R\x06stepId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x02 \x01(\tR\tskillName\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\xb5\x03\n" +
	"\n" +
	"OpsService\x12b\n" +
	"\n" +
	"SubmitTask\x12\x1f.opskills.ops.SubmitTaskRequest\x1a\x19.opskills.common.Response\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12o\n" +
	"\rGetTaskStatus\x12\".opskills.ops.GetTaskStatusRequest\x1a\x19.opskills.common.Response\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/tasks/{task_id}\x12]\n" +
	"\tListTasks\x12\x1e.opskills.ops.ListTasksRequest\x1a\x19.opskills.common.Response\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/tasks\x12s\n" +
	"\n" +
	"CancelTask\x12\x1f.opskills.ops.CancelTaskRequest\x1a\x19.opskills.common.Response\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/tasks/{task_id}/cancelB+Z)github.com/hb-chen/opskills/proto/ops;opsb\x06proto3"

var (
	file_proto_ops_ops_proto_rawDescOnce sync.Once
	file_proto_ops_ops_proto_rawDescData []byte
)

func file_proto_ops_ops_proto_rawDescGZIP() []byte {
	file_proto_ops_ops_proto_rawDescOnce.Do(func() {
		file_proto_ops_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ops_ops_proto_rawDesc), len(file_proto_ops_ops_proto_rawDesc)))
	})
	return file_proto_ops_ops_proto_rawDescData
}

var file_proto_ops_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ops_ops_proto_goTypes = []any{
	(*SubmitTaskRequest)(nil),    // 0: opskills.ops.SubmitTaskRequest
	(*GetTaskStatusRequest)(nil), // 1: opskills.ops.GetTaskStatusRequest
	(*ListTasksRequest)(nil),     // 2: opskills.ops.ListTasksRequest
	(*CancelTaskRequest)(nil),    // 3: opskills.ops.CancelTaskRequest
	(*Task)(nil),                 // 4: opskills.ops.Task
	(*StepResult)(nil),           // 5: opskills.ops.StepResult
	nil,                          // 6: opskills.ops.SubmitTaskRequest.ParamsEntry
	(*common.Response)(nil),      // 7: opskills.common.Response
}
var file_proto_ops_ops_proto_depIdxs = []int32{
	6, // 0: opskills.ops.SubmitTaskRequest.params:type_name -> opskills.ops.SubmitTaskRequest.ParamsEntry
	5, // 1: opskills.ops.Task.results:type_name -> opskills.ops.StepResult
	0, // 2: opskills.ops.OpsService.SubmitTask:input_type -> opskills.ops.SubmitTaskRequest
	1, // 3: opskills.ops.OpsService.GetTaskStatus:input_type -> opskills.ops.GetTaskStatusRequest
	2, // 4: opskills.ops.OpsService.ListTasks:input_type -> opskills.ops.ListTasksRequest
	3, // 5: opskills.ops.OpsService.CancelTask:input_type -> opskills.ops.CancelTaskRequest
	7, // 6: opskills.ops.OpsService.SubmitTask:output_type -> opskills.common.Response
	7, // 7: opskills.ops.OpsService.GetTaskStatus:output_type -> opskills.common.Response
	7, // 8: opskills.ops.OpsService.ListTasks:output_type -> opskills.common.Response
	7, // 9: opskills.ops.OpsService.CancelTask:output_type -> opskills.common.Response
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ops_ops_proto_init() }
func file_proto_ops_ops_proto_init() {
	if File_proto_ops_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ops_ops_proto_rawDesc), len(file_proto_ops_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ops_ops_proto_goTypes,
		DependencyIndexes: file_proto_ops_ops_proto_depIdxs,
		MessageInfos:      file_proto_ops_ops_proto_msgTypes,
	}.Build()
	File_proto_ops_ops_proto = out.File
	file_proto_ops_ops_proto_goTypes = nil
	file_proto_ops_ops_proto_depIdxs = nil
}
